package htmlcolors

// ColorNames maps names to hex value. *A duplicate name
// will raise a compile-time error.* Might be duplicate
// colors ... (same color, different names). All colornames
// are lowercase for comparisons
// Duplicate color values exist in this table, but are skinned out
// in htmlColor.init().
// hex values mapped to multiple names should be RETAINED in this
// list for use of StringToColor. Similar colornames may be differentiated
// by adding a digit iff they map to different hex values.
// Same name-value combinations should be removed. Prefer names
// WITHOUT a space.

var ColorNames = map[string]string{
	"acid green":               "#b0bf1a",
	"aero blue":                "#c9ffe5",
	"african violet":           "#b284be",
	"air force blue (usaf)":    "#00308f",
	"air superiority blue":     "#72a0c1",
	"alabama crimson":          "#a32638",
	"alabama crimson1":         "#af002a",
	"algae green":              "#64e986",
	"alice blue":               "#f0f8ff",
	"aliceblue":                "#f0f8ff",
	"alien green":              "#6cc417",
	"alloy orange":             "#c46210",
	"almond buff":              "#d1b894",
	"almond":                   "#efdecd",
	"almost mauve":             "#eadedb",
	"amaranth pink":            "#f19cbb",
	"amaranth purple":          "#ab274f",
	"amaranth":                 "#e52b50",
	"amazon":                   "#3b7a57",
	"amber (sae/ece)":          "#ff7e00",
	"american rose":            "#ff033e",
	"amethyst orchid":          "#926aa6",
	"amethyst":                 "#9966cc",
	"amzn_0001":                "#630f32", /* red matte */
	"amzn_0002":                "#0F6340", /* greenish matte */
	"android green":            "#a4c639",
	"anti flash white":         "#f2f3f4",
	"antique brass":            "#cd9575",
	"antique bronze":           "#665d1e",
	"antique fuchsia":          "#915c83",
	"antique ruby":             "#841b2d",
	"antique white":            "#faebd7",
	"antiquewhite":             "#faebd7",
	"apple green":              "#8db600",
	"apricot":                  "#fbceb1",
	"aqua sky":                 "#7ac5c5",
	"aqua":                     "#00ffff",
	"aquamarine":               "#7fffd4",
	"arcadia":                  "#00a591",
	"arctic lime":              "#d0ff14",
	"army brown":               "#827b60",
	"army green":               "#4b5320",
	"arsenic":                  "#3b444b",
	"artichoke":                "#8f9779",
	"ash gray":                 "#666362",
	"ash grey":                 "#b2beb5",
	"asparagus":                "#87a96b",
	"aspen gold":               "#ffd662",
	"atomic tangerine":         "#ff9966",
	"aureolin":                 "#fdee00",
	"aurometalsaurus":          "#6e7f80",
	"autumn maple":             "#d2691e",
	"avocado green":            "#b2c248",
	"avocado":                  "#568203",
	"aztech purple":            "#893bff",
	"azure mist":               "#f0ffff",
	"azure1":                   "#007fff",
	"azure":                    "#f0ffff",
	"baby blue eyes":           "#a1caf1",
	"baby blue1":               "#89cff0",
	"baby blue":                "#95b9c7",
	"baby powder":              "#fefefa",
	"ball blue":                "#21abcd",
	"ballet slipper":           "#f3d6e4",
	"banana mania":             "#fae7b5",
	"banana yellow":            "#ffe135",
	"barbie pink":              "#e0218a",
	"barn red":                 "#7c0a02",
	"bashful pink":             "#c25283",
	"basket ball orange":       "#f88158",
	"battleship gray":          "#848482",
	"bazaar":                   "#98777b",
	"bean red":                 "#f75d59",
	"beaver":                   "#9f8170",
	"bee yellow":               "#e9ab17",
	"beer":                     "#fbb117",
	"beetle green":             "#4c787e",
	"beige":                    "#f5f5dc",
	"big dip o’ruby":           "#9c2542",
	"biking red":               "#77212e",
	"bisque":                   "#ffe4c4",
	"bistre":                   "#3d2b1f",
	"bitter lemon":             "#cae00d",
	"bitter lime":              "#648c11",
	"bitter lime1":             "#bfff00",
	"bittersweet shimmer":      "#bf4f51",
	"bittersweet":              "#fe6f5e",
	"black bean":               "#3d0c02",
	"black cat":                "#413839",
	"black cow":                "#4c4646",
	"black eel":                "#463e3f",
	"black leather jacket":     "#253529",
	"black":                    "#000000",
	"blanched almond":          "#ffebcd",
	"blanchedalmond":           "#ffebcd",
	"blast off bronze":         "#a57164",
	"bleu de france":           "#318ce7",
	"blizzard blue":            "#ace5ee",
	"blond":                    "#faf0be",
	"blonde":                   "#fbf6d9",
	"blood red":                "#7e3517",
	"blooming dahlia":          "#ec9787",
	"blossom pink":             "#f9b7ff",
	"blue (crayola)":           "#1f75fe",
	"blue (munsell)":           "#0093af",
	"blue (ncs)":               "#0087bd",
	"blue (pigment)":           "#333399",
	"blue (ryb)":               "#0247fe",
	"blue angel":               "#b7ceec",
	"blue bell":                "#a2a2d0",
	"blue diamond":             "#4ee2ec",
	"blue dress":               "#157dec",
	"blue eyes":                "#1569c7",
	"blue gray":                "#98afc7",
	"blue green":               "#0d98ba",
	"blue green1":              "#7bccb5",
	"blue hosta":               "#77bfc7",
	"blue iris":                "#595ca1",
	"blue ivy":                 "#3090c7",
	"blue jay":                 "#2b547e",
	"blue koi":                 "#659ec7",
	"blue lagoon":              "#8eebec",
	"blue lotus":               "#6960ec",
	"blue orchid":              "#1f45fc",
	"blue ribbon":              "#306eff",
	"blue sapphire":            "#126180",
	"blue turquoise":           "#4fb0ae",
	"blue violet":              "#8a2be2",
	"blue whale":               "#342d7e",
	"blue yonder":              "#5072a7",
	"blue zircon":              "#57feff",
	"blue":                     "#0000ff",
	"blueberry blue":           "#0041c2",
	"blueberry":                "#4f86f7",
	"bluebonnet":               "#1c1cf0",
	"bluestone":                "#577284",
	"blueviolet":               "#8a2be2",
	"blush pink":               "#e6a9ec",
	"blush red":                "#e56e94",
	"blush":                    "#de5d83",
	"bondi blue":               "#0095b6",
	"bone":                     "#e3dac9",
	"bored accent green":       "#dde26a",
	"boston university red":    "#cc0000",
	"bottle green":             "#006a4e",
	"boysenberry":              "#873260",
	"brandeis blue":            "#0070ff",
	"brass":                    "#b5a642",
	"brick red":                "#cb4154",
	"bright cerulean":          "#1dacd6",
	"bright gold":              "#fdd017",
	"bright green":             "#66ff00",
	"bright lavender":          "#bf94e4",
	"bright lilac":             "#d891ef",
	"bright maroon":            "#c32148",
	"bright navy blue":         "#1974d2",
	"bright neon pink":         "#f433ff",
	"bright turquoise":         "#08e8de",
	"bright ube":               "#d19fe8",
	"brilliant rose":           "#ff55a3",
	"brink pink":               "#fb607f",
	"british racing green":     "#004225",
	"bronze yellow":            "#737000",
	"bronze":                   "#cd7f32",
	"brown (traditional)":      "#964b00",
	"brown bear":               "#835c3b",
	"brown granite":            "#615550",
	"brown sugar":              "#e2a76f",
	"brown":                    "#a52a2a",
	"bubble gum":               "#ffc1cc",
	"bubbles":                  "#e7feff",
	"bud green":                "#7bb661",
	"buff":                     "#f0dc82",
	"bulgarian rose":           "#480607",
	"bullet shell":             "#af9b60",
	"burgundy":                 "#800020",
	"burgundy1":                "#8c001a",
	"burly wood":               "#deb887",
	"burlywood":                "#deb887",
	"burnt coral":              "#e9897e",
	"burnt orange":             "#cc5500",
	"burnt pink":               "#c12267",
	"burnt umber":              "#8a3324",
	"butter rum":               "#c48f65",
	"buttercream":              "#efe1ce",
	"buttercup":                "#fae03c",
	"butterfly blue":           "#38acec",
	"byzantine":                "#bd33a4",
	"byzantium":                "#702963",
	"cadet blue":               "#5f9ea0",
	"cadet grey":               "#91a3b0",
	"cadet":                    "#536872",
	"cadetblue":                "#5f9ea0",
	"cadillac pink":            "#e38aae",
	"cadmium green":            "#006b3c",
	"cadmium orange":           "#ed872d",
	"cadmium red":              "#e30022",
	"cadmium yellow":           "#fff600",
	"café noir":                "#4b3621",
	"cal poly green":           "#1e4d2b",
	"calamansi":                "#fcffa4",
	"cambridge blue":           "#a3c1ad",
	"camel brown":              "#c19a6b",
	"cameo pink":               "#efbbcc",
	"camouflage green":         "#78866b",
	"canary yellow":            "#ffef00",
	"candy apple red":          "#ff0800",
	"cantaloupe":               "#ffa62f",
	"caput mortuum":            "#592720",
	"caramel":                  "#c68e17",
	"carbon gray":              "#625d5d",
	"cardinal":                 "#c41e3a",
	"caribbean green":          "#00cc99",
	"carmine pink":             "#eb4c42",
	"carmine red":              "#ff0038",
	"carmine":                  "#960018",
	"carnation pink":           "#ffa6c9",
	"carnation pink1":          "#f778a1",
	"carolina blue":            "#99badd",
	"carrot orange":            "#ed9121",
	"catalina blue":            "#062a78",
	"catawba":                  "#703642",
	"cedar chest":              "#c95a49",
	"ceil":                     "#92a1cf",
	"celadon green":            "#2f847c",
	"celadon":                  "#ace1af",
	"celeste":                  "#50ebec",
	"celestial blue":           "#4997d0",
	"cerise pink":              "#ec3b83",
	"cerulean blue":            "#2a52be",
	"cerulean frost":           "#6d9bc3",
	"cerulean":                 "#007ba7",
	"cerulean1":                "#9bb7d6",
	"ceylon yellow":            "#d5ae41",
	"cg blue":                  "#007aa5",
	"cg red":                   "#e03c31",
	"chamoisee":                "#a0785a",
	"champagne":                "#f7e7ce",
	"charcoal":                 "#36454f",
	"charcoal1":                "#34282c",
	"charleston green":         "#232b2b",
	"chartreuse":               "#7fff00",
	"chartreuse1":              "#dfff00",
	"chartreuse2":              "#8afb17",
	"cherry blossom pink":      "#ffb7c5",
	"cherry red":               "#c24641",
	"cherry tomato":            "#e94b3c",
	"cherry":                   "#de3163",
	"chestnut red":             "#c34a2c",
	"chestnut":                 "#954535",
	"chili oil":                "#944743",
	"chili pepper":             "#9c1b31",
	"chilli pepper":            "#c11b17",
	"china rose":               "#a8516e",
	"chinese green":            "#d0db61",
	"chinese red":              "#aa381e",
	"chinese violet":           "#856088",
	"chocolate (traditional)":  "#7b3f00",
	"chocolate":                "#d2691e",
	"chocolate1":               "#c85a17",
	"chrome yellow":            "#ffa700",
	"cinereous":                "#98817b",
	"cinnamon":                 "#c58917",
	"citrine":                  "#e4d00a",
	"citron":                   "#9fa91f",
	"claret":                   "#7f1734",
	"classic blue":             "#0f4c81",
	"classic rose":             "#fbcce7",
	"cloudy gray":              "#6d6968",
	"clover green":             "#3ea055",
	"coal":                     "#7cb9e8",
	"cobalt blue":              "#0020c2",
	"cobalt":                   "#0047ab",
	"cocoa brown":              "#d2691e",
	"coconut milk":             "#f0ede5",
	"coconut":                  "#965a3e",
	"coffee":                   "#6f4e37",
	"columbia blue":            "#9bddff",
	"columbia blue1":           "#87afc7",
	"construction cone orange": "#f87431",
	"cookie brown":             "#c7a317",
	"cool black":               "#002e63",
	"copper penny":             "#ad6f69",
	"copper red":               "#cb6d51",
	"copper rose":              "#996666",
	"copper":                   "#b87333",

	"coquelicot": "#ff3800",
	"coral blue": "#afdcec",
	"coral pink": "#f88379",
	"coral red":  "#ff4040",

	"coral":                 "#ff7f50",
	"cordovan":              "#893f45",
	"corn flower blue":      "#6495ed",
	"corn silk":             "#fff8dc",
	"corn yellow":           "#fff380",
	"cornell red":           "#b31b1b",
	"cornflower blue":       "#6495ed",
	"cornflowerblue":        "#6495ed",
	"cornsilk":              "#fff8dc",
	"cosmic latte":          "#fff8e7",
	"cotton candy":          "#ffbcd9",
	"cotton candy1":         "#fcdfff",
	"cranberry":             "#9f000f",
	"cream":                 "#fffdd0",
	"crimson glory":         "#be0032",
	"crimson":               "#dc143c",
	"crimson1":              "#e238ec",
	"crocus petal":          "#be9ec9",
	"crocus purple":         "#9172ec",
	"crystal blue":          "#5cb3ff",
	"crème de pêche":        "#f5d6c6",
	"cyan (process)":        "#00b7eb",
	"cyan opaque":           "#92c7c7",
	"cyan":                  "#00ffff", // duplicate name for aqua
	"cyber grape":           "#58427c",
	"cyber yellow":          "#ffd300",
	"daffodil":              "#ffff31",
	"dandelion":             "#f0e130",
	"dark blue gray":        "#666699",
	"dark blue":             "#00008b",
	"dark byzantium":        "#5d3954",
	"dark candy apple red":  "#a40000",
	"dark carnation pink":   "#c12283",
	"dark cerulean":         "#08457e",
	"dark cheddar":          "#e08119",
	"dark chestnut":         "#986960",
	"dark coral":            "#cd5b45",
	"dark cyan":             "#008b8b",
	"dark forest green":     "#254117",
	"dark goldenrod":        "#af7817",
	"dark gray":             "#a9a9a9",
	"dark grey":             "#a9a9a9",
	"dark imperial blue":    "#00416a",
	"dark khaki":            "#bdb76b",
	"dark lavender":         "#734f96",
	"dark lemon lime":       "#8bbe1b",
	"dark liver":            "#534b4f",
	"dark magenta":          "#8b008b",
	"dark midnight blue":    "#000036",
	"dark midnight blue1":   "#003366",
	"dark moss green":       "#4a5d23",
	"dark olive green":      "#556b2f",
	"dark orange":           "#ff8c00",
	"dark orange1":          "#f88017",
	"dark orchid":           "#9932cc",
	"dark orchid1":          "#7d1b7e",
	"dark pastel blue":      "#779ecb",
	"dark pastel green":     "#03c03c",
	"dark pastel purple":    "#966fd6",
	"dark pastel red":       "#c23b22",
	"dark pink":             "#e75480",
	"dark powder blue":      "#000039",
	"dark puce":             "#4f3a3c",
	"dark raspberry":        "#872657",
	"dark red":              "#8b0000",
	"dark salmon":           "#e9967a",
	"dark scarlet":          "#560319",
	"dark sea green":        "#8fbc8f",
	"dark sea green1":       "#8bb381",
	"dark sienna":           "#3c1414",
	"dark sky blue":         "#8cbed6",
	"dark slate blue":       "#483d8b",
	"dark slate blue1":      "#2b3856",
	"dark slate gray":       "#2f4f4f",
	"dark slate grey":       "#25383c",
	"dark spring green":     "#177245",
	"dark tan":              "#918151",
	"dark tangerine":        "#ffa812",
	"dark terra cotta":      "#cc4e5c",
	"dark turquoise":        "#00ced1",
	"dark turquoise1":       "#3b9c9c",
	"dark vanilla":          "#d1bea8",
	"dark violet":           "#9400d3",
	"dark violet1":          "#842dce",
	"dark yellow":           "#9b870c",
	"darkblue":              "#00008b",
	"darkcyan":              "#008b8b",
	"darkgoldenrod":         "#b8860b",
	"darkgray":              "#a9a9a9",
	"darkgreen":             "#006400",
	"darkgrey":              "#a9a9a9",
	"darkkhaki":             "#bdb76b",
	"darkmagenta":           "#8b008b",
	"darkolivegreen":        "#556b2f",
	"darkorange":            "#ff8c00",
	"darkred":               "#8b0000",
	"darksalmon":            "#e9967a",
	"darkseagreen":          "#8fbc8f",
	"darkslateblue":         "#483d8b",
	"darkslategray":         "#2f4f4f",
	"darkslategrey":         "#2f4f4f",
	"darkturquoise":         "#00ced1",
	"darkviolet":            "#9400d3",
	"dartmouth green":       "#00703c",
	"davy’s grey":           "#555555",
	"day sky blue":          "#82caff",
	"debian red":            "#d70a53",
	"deep carmine pink":     "#ef3038",
	"deep carmine":          "#a9203e",
	"deep carrot orange":    "#e9692c",
	"deep cerise":           "#da3287",
	"deep chestnut":         "#b94e48",
	"deep fuchsia":          "#c154c1",
	"deep jungle green":     "#004b49",
	"deep lemon":            "#f5c71a",
	"deep lilac":            "#9955bb",
	"deep magenta":          "#cc00cc",
	"deep peach":            "#ffcba4",
	"deep pink":             "#ff1493",
	"deep pink1":            "#f52887",
	"deep puce":             "#a95c68",
	"deep ruby":             "#843f5b",
	"deep saffron":          "#ff9933",
	"deep sky blue":         "#00bfff",
	"deep sky blue1":        "#3bb9ff",
	"deep space sparkle":    "#4a646c",
	"deep taupe":            "#7e5e60",
	"deep tuscan red":       "#66424d",
	"deeppink":              "#ff1493",
	"deepskyblue":           "#00bfff",
	"deer":                  "#ba8759",
	"denim blue":            "#79baec",
	"denim dark blue":       "#151b8d",
	"denim":                 "#1560bd",
	"desert mist":           "#e0b589",
	"desert sand":           "#edc9af",
	"desire":                "#ea3c53",
	"diamond":               "#b9f2ff",
	"dim gray":              "#696969",
	"dim grey":              "#696969",
	"dimgray":               "#696969",
	"dimgrey":               "#696969",
	"dimorphotheca magenta": "#e3319d",
	"dirt":                  "#9b7653",
	"dodger blue":           "#1e90ff",
	"dodger blue1":          "#1589ff",
	"dodgerblue":            "#1e90ff",
	"dogwood rose":          "#d71868",
	"dollar bill green":     "#85bb65",
	"dollar bill":           "#85bb65",
	"donkey brown":          "#664c28",
	"dragon green":          "#6afb92",
	"duke blue":             "#00009c",
	"dull purple":           "#7f525d",
	"dust storm":            "#e5ccc9",
	"dutch white":           "#efdfbb",
	"earth blue":            "#0000a0",
	"earth yellow":          "#e1a95f",
	"ebony":                 "#555d50",
	"eclipse":               "#343148",
	"eden":                  "#264e36",
	"eggplant":              "#614051",

	"eggshell":             "#f0ead6",
	"egyptian blue":        "#1034a6",
	"electric blue":        "#7df9ff",
	"electric blue1":       "#9afeff",
	"electric crimson":     "#ff003f",
	"electric cyan":        "#00ffff",
	"electric indigo":      "#6f00ff",
	"electric lavender":    "#f4bbff",
	"electric lime":        "#ccff00",
	"electric purple":      "#bf00ff",
	"electric ultramarine": "#3f00ff",
	"emerald green":        "#5ffb17",
	"emerald":              "#169c78",
	"eminence":             "#6c3082",
	"emperador":            "#6c4f3d",
	"english green":        "#1b4d3e",
	"english lavender":     "#b48395",
	"english red":          "#ab4b52",
	"eton blue":            "#96c8a2",
	"eucalyptus":           "#44d7a8",
	"evening blue":         "#2a293e",
	"fall leaf brown":      "#c8b560",
	"falu red":             "#801818",
	"fandango pink":        "#de5285",
	"fandango":             "#b53389",
	"fawn":                 "#e5aa70",
	"feldgrau":             "#4d5d53",
	"fern green":           "#667c26",
	"ferrari red":          "#ff2800",
	"field drab":           "#6c541e",
	"fiesta":               "#dd4132",
	"fire brick":           "#b22222",
	"fire engine red":      "#ce2029",
	"firebrick":            "#b22222",
	"firebrick1":           "#800517",
	"flame":                "#f2552c",
	"flamingo pink":        "#fc8eac",
	"flamingo pink1":       "#f9a7b0",
	"flattery":             "#6b4423",
	"flavescent":           "#f7e98e",
	"flax":                 "#eedc82",
	"flirt":                "#a2006d",
	"floral white":         "#fffaf0",
	"floralwhite":          "#fffaf0",
	"fluorescent orange":   "#ffbf00",
	"fluorescent pink":     "#ff1493",
	"folly":                "#ff004f",
	"forest green":         "#4e9258",
	"forestgreen":          "#228b22",
	"french bistre":        "#856d4d",
	"french blue":          "#0072bb",
	"french blue1":         "#0072b5",
	"french fuchsia":       "#fd3f92",
	"french lime":          "#9efd38",
	"french mauve":         "#d473d4",
	"french pink":          "#fd6c9e",
	"french puce":          "#4e1609",
	"french raspberry":     "#c72c48",
	"french rose":          "#f64a8a",
	"french sky blue":      "#77b5fe",
	"french wine":          "#ac1e44",
	"fresh air":            "#a6e7ff",
	"frog green":           "#99c68e",
	"fruit dove":           "#ce5b78",
	"fuchsia pink":         "#ff77ff",
	"fuchsia purple":       "#cc397b",
	"fuchsia rose":         "#c74375",
	"fuchsia":              "#ff00ff",
	"fulvous":              "#e48400",
	"fuschia rose":         "#c94476",
	"fuzzy wuzzy":          "#cc6666",
	"gainsboro":            "#dcdcdc",
	"galaxy blue":          "#2a4b7c",
	"gamboge":              "#e49b0f",
	"generic viridian":     "#007f66",
	"ghost white":          "#f8f8ff",
	"ghostwhite":           "#f8f8ff",
	"giants orange":        "#fe5a1d",
	"gin":                  "#d8e4bc",
	"ginger brown":         "#c9be62",
	"ginger":               "#b06500",
	"glacial blue ice":     "#368bc1",
	"glaucous":             "#6082b6",
	"glitter":              "#e6e8fa",
	"go green":             "#00ab66",
	"gold (metallic)":      "#d4af37",
	"gold fusion":          "#85754e",
	"gold":                 "#ffd700",
	"golden brown":         "#eac117",
	"golden lime":          "#9c9a40",
	"golden poppy":         "#fcc200",
	"golden yellow":        "#ffdf00",
	"goldenrod":            "#daa520",
	"goldenrod1":           "#edda74",
	"granite":              "#837e7c",
	"granny smith apple":   "#a8e4a0",
	"grape":                "#6f2da8",
	"grape1":               "#5e5a80",
	"grapefruit":           "#dc381f",
	"gray (x11 gray)":      "#bebebe",
	"gray asparagus":       "#465945",
	"gray blue":            "#8c92ac",
	"gray cloud":           "#b6b6b4",
	"gray dolphin":         "#5c5858",
	"gray goose":           "#d1d0ce",
	"gray wolf":            "#504a4b",
	"gray":                 "#808080",
	"gray2":                "#736f6e",
	"grayish turquoise":    "#5e7d7e",
	"green (crayola)":      "#1cac78",
	"green (munsell)":      "#00a877",
	"green (ncs)":          "#009f6b",
	"green (pigment)":      "#00a550",
	"green (ryb)":          "#66b032",
	"green apple":          "#4cc417",
	"green ash":            "#a0daa9",
	"green flash":          "#79c753",
	"green onion":          "#6aa121",
	"green peas":           "#89c35c",
	"green snake":          "#6cbb3c",
	"green thumb":          "#b5eaaa",
	"green yellow":         "#b1fb17",
	"green":                "#008000",
	"greenery":             "#88b04b",
	"greenish blue":        "#307d7e",
	"greenyellow":          "#adff2f",
	"grenadine":            "#dc4c46",

	"grey":              "#808080",
	"grullo":            "#a99a86",
	"guacamole":         "#797b3a",
	"gunmetal":          "#2c3539",
	"halloween orange":  "#e66c2c",
	"han blue":          "#446ccf",
	"han purple":        "#5218fa",
	"hansa yellow":      "#e9d66b",
	"harbor mist":       "#b4b7ba",
	"harlequin":         "#3fff00",
	"harvard crimson":   "#c90016",
	"harvest gold":      "#ede275",
	"hazel green":       "#617c58",
	"hazelnut":          "#cfb095",
	"heliotrope purple": "#d462ff",
	"heliotrope":        "#df73ff",
	"hollywood cerise":  "#f400a1",
	"honey dew":         "#f0fff0",
	"honeydew":          "#f0fff0",

	"honeysuckle":                        "#da4f70",
	"honolulu blue":                      "#006db0",
	"honolulu blue1":                     "#007fbf",
	"hooker green":                       "#49796b",
	"hot magenta":                        "#ff1dce",
	"hot pink":                           "#ff69b4",
	"hot pink1":                          "#f660ab",
	"hotpink":                            "#ff69b4",
	"hummingbird green":                  "#7fe817",
	"hunter green":                       "#355e3b",
	"iceberg":                            "#71a6d2",
	"iceberg1":                           "#56a5ec",
	"iced coffee":                        "#b18f6a",
	"icterine":                           "#fcf75e",
	"iguana green":                       "#9cb071",
	"illuminating emerald":               "#319177",
	"illuminating":                       "#f5df4d",
	"imperial blue":                      "#002395",
	"imperial red":                       "#ed2939",
	"imperial":                           "#602f6b",
	"inchworm":                           "#b2ec5d",
	"independence":                       "#4c516d",
	"india green":                        "#138808",
	"indian red":                         "#cd5c5c",
	"indian yellow":                      "#e3a857",
	"indianred":                          "#cd5c5c",
	"indigo":                             "#4b0082",
	"inkwell":                            "#363945",
	"international klein blue":           "#002fa7",
	"international orange (engineering)": "#ba160c",
	"international orange (golden gate bridge)": "#c0362c",
	"international orange":                      "#ff4f00",
	"iridium":                                   "#3d3c3a",
	"iris":                                      "#5a4fcf",
	"isabelline":                                "#f4f0ec",
	"islamic green":                             "#009900",
	"island paradise":                           "#95dee3",
	"italian sky blue":                          "#b2ffff",
	"ivory":                                     "#fffff0",
	"jade green":                                "#5efb6e",
	"jade":                                      "#00a86b",
	"japanese carmine":                          "#9d2933",
	"japanese indigo":                           "#264348",
	"japanese violet":                           "#5b3256",
	"jasmine purple":                            "#a23bec",
	"jasper":                                    "#d73b3e",
	"jazzberry jam":                             "#a50b5e",
	"jeans blue":                                "#a0cfec",
	"jelly bean":                                "#da614e",
	"jellyfish":                                 "#46c7c7",
	"jester red":                                "#9e1030",
	"jet gray":                                  "#616d7e",
	"jet":                                       "#343434",
	"jonquil":                                   "#f4ca16",
	"jordy blue":                                "#8ab9f1",
	"june bud":                                  "#bdda57",
	"jungle green":                              "#29ab87",
	"jungle green1":                             "#347c2c",
	"kale":                                      "#5a7247",
	"kelly green":                               "#4cc552",
	"kenyan copper":                             "#7c1c05",
	"keppel":                                    "#3ab09e",
	"key lime":                                  "#e8f48c",
	"khaki rose":                                "#c5908e",
	"khaki":                                     "#c3b091",
	"khaki1":                                    "#f0e68c",
	"khaki2":                                    "#ada96e",
	"kobi":                                      "#e79fc4",
	"kombu green":                               "#354230",
	"ku crimson":                                "#e8000d",
	"la salle green":                            "#087830",
	"languid lavender":                          "#d6cadd",
	"lapis blue":                                "#15317e",
	"lapis blue1":                               "#004b8d",
	"lapis lazuli":                              "#26619c",
	"laser lemon":                               "#fefe22",
	"laurel green":                              "#a9ba9d",
	"lava red":                                  "#e42217",
	"lava":                                      "#cf1020",
	"lavender (floral)":                         "#b57edc",
	"lavender blue":                             "#e3e4fa",
	"lavender blush":                            "#fff0f5",
	"lavender gray":                             "#c4c3d0",
	"lavender magenta":                          "#ee82ee",
	"lavender mist":                             "#e6e6fa",
	"lavender pink":                             "#fbaed2",
	"lavender pinocchio":                        "#ebdde2",
	"lavender purple":                           "#967bb6",
	"lavender rose":                             "#fba0e3",
	"lavender":                                  "#e6e6fa",
	"lavenderblush":                             "#fff0f5",
	"lawn green":                                "#87f717",
	"lawngreen":                                 "#7cfc00",
	"lemon chiffon":                             "#fffacd",
	"lemon curry":                               "#cca01d",
	"lemon glacier":                             "#fdff00",
	"lemon lime":                                "#e3ff00",
	"lemon meringue":                            "#f6eabe",
	"lemon yellow":                              "#fff44f",
	"lemon":                                     "#fff700",
	"lemonchiffon":                              "#fffacd",
	"liberty":                                   "#545aa7",
	"light apricot":                             "#fdd5b1",
	"light aquamarine":                          "#93ffe8",
	"light blue":                                "#add8e6",
	"light blue1":                               "#addfff",
	"light brown":                               "#b5651d",
	"light carmine pink":                        "#e66771",
	"light coral":                               "#f08080",
	"light cornflower blue":                     "#93ccea",
	"light crimson":                             "#f56991",
	"light cyan":                                "#e0ffff",
	"light deep pink":                           "#ff5ccd",
	"light fuchsia pink":                        "#f984ef",
	"light goldenrod yellow":                    "#fafad2",
	"light gray":                                "#d3d3d3",
	"light green":                               "#90ee90",
	"light grey":                                "#d3d3d3",
	"light hot pink":                            "#ffb3de",
	"light jade":                                "#c3fdb8",
	"light medium orchid":                       "#d39bcb",
	"light moss green":                          "#addfad",
	"light orchid":                              "#e6a8d7",
	"light pastel purple":                       "#b19cd9",
	"light pink":                                "#ffb6c1",
	"light pink1":                               "#faafba",
	"light red ochre":                           "#e97451",
	"light salmon pink":                         "#ff9999",
	"light salmon":                              "#ffa07a",
	"light sea green":                           "#20b2aa",
	"light sea green1":                          "#3ea99f",
	"light sky blue":                            "#87cefa",

	"light slate blue":     "#736aff",
	"light slate gray":     "#778899",
	"light slate gray1":    "#6d7b8d",
	"light slate grey":     "#778899",
	"light slate":          "#ccffff",
	"light steel blue1":    "#b0c4de",
	"light steel blue":     "#728fce",
	"light taupe":          "#b38b6d",
	"light thulian pink":   "#e68fac",
	"light yellow":         "#ffffe0",
	"lightblue":            "#add8e6",
	"lightcoral":           "#f08080",
	"lightcyan":            "#e0ffff",
	"lightgoldenrodyellow": "#fafad2",
	"lightgray":            "#d3d3d3",
	"lightgreen":           "#90ee90",
	"lightgrey":            "#d3d3d3",
	"lightpink":            "#ffb6c1",
	"lightsalmon":          "#ffa07a",
	"lightseagreen":        "#20b2aa",
	"lightskyblue":         "#87cefa",
	"lightslategray":       "#778899",
	"lightslategrey":       "#778899",
	"lightsteelblue":       "#b0c4de",
	"lightyellow":          "#ffffe0",
	"lilac grey":           "#9896a4",
	"lilac":                "#c8a2c8",
	"lime green":           "#41a317",
	"lime pulp":            "#d1e189",
	"lime punch":           "#bfd641",
	"lime":                 "#00ff00",
	"limegreen":            "#32cd32",
	"limelight":            "#f1ea7f",
	"limerick":             "#9dc209",
	"limpet shell":         "#98ddde",
	"lincoln green":        "#195905",
	"linen":                "#faf0e6",

	"lipstick pink":            "#c48793",
	"little boy blue":          "#6ca0dc",
	"little boy blue1":         "#6f9fd8",
	"liver chestnut":           "#987456",
	"livid":                    "#6699cc",
	"living coral":             "#ff6f61",
	"love red":                 "#e41b17",
	"lovely purple":            "#7f38ec",
	"lumber":                   "#ffe4cd",
	"lust":                     "#e62020",
	"macaroni and cheese":      "#f2bb66",
	"macaw blue green":         "#43bfc7",
	"magenta (dye)":            "#ca1f7b",
	"magenta (process)":        "#ff0090",
	"magenta haze":             "#9f4576",
	"magenta":                  "#ff00ff", // alternate name: magenta
	"magic mint":               "#aaf0d1",
	"magnolia":                 "#f8f4ff",
	"mahogany":                 "#c04000",
	"maize":                    "#fbec5d",
	"majorelle blue":           "#6050dc",
	"malachite":                "#0bda51",
	"manatee":                  "#979aaa",
	"mango mojito":             "#d69c2f",
	"mango orange":             "#ff8040",
	"mango tango":              "#ff8243",
	"mantis":                   "#74c365",
	"marble blue":              "#566d7e",
	"mardi gras":               "#880085",
	"margarita":                "#b0c24a",
	"marigold":                 "#fdac53",
	"marina":                   "#4f84c4",
	"maroon":                   "#800000",
	"maroon1":                  "#810541",
	"marsala":                  "#955251",
	"martini olive":            "#766f57",
	"mauve":                    "#e0b0ff",
	"mauvelous":                "#ef98aa",
	"maximum green yellow":     "#d9e650",
	"maya blue":                "#73c2fb",
	"meadowlark":               "#ecdb54",
	"meat brown":               "#e5b73b",
	"medium aquamarine":        "#66cdaa",
	"medium aquamarine1":       "#348781",
	"medium blue":              "#0000cd",
	"medium candy apple red":   "#e2062c",
	"medium electric blue":     "#035096",
	"medium forest green":      "#347235",
	"medium jungle green":      "#1c352d",
	"medium orchid":            "#ba55d3",
	"medium orchid1":           "#b048b5",
	"medium purple":            "#9370db",
	"medium purple1":           "#8467d7",
	"medium red violet":        "#bb3385",
	"medium ruby":              "#aa4069",
	"medium sea green":         "#306754",
	"medium sky blue":          "#80daeb",
	"medium slate blue":        "#7b68ee",
	"medium spring bud":        "#c9dc87",
	"medium spring green":      "#348017",
	"medium taupe":             "#674c47",
	"medium turquoise":         "#48d1cc",
	"medium turquoise1":        "#48cccd",
	"medium tuscan red":        "#79443b",
	"medium vermilion":         "#d9603b",
	"medium violet red":        "#c71585",
	"medium violet red1":       "#ca226b",
	"mediumaquamarine":         "#66cdaa",
	"mediumblue":               "#0000cd",
	"mediumorchid":             "#ba55f3",
	"mediumpurple":             "#9370db",
	"mediumseagreen":           "#3cb371",
	"mediumslateblue":          "#7b68ee",
	"mediumspringgreen":        "#00fa9a",
	"mediumturquoise":          "#48d1cc",
	"mediumvioletred":          "#c71585",
	"meerkat":                  "#a9754f",
	"mellow apricot":           "#f8b878",
	"mellow yellow":            "#f8de7e",
	"melon":                    "#fdbcb4",
	"metallic seaweed":         "#0a7e8c",
	"metallic silver":          "#bcc6cc",
	"metallic sunburst":        "#9c7c38",
	"mexican pink":             "#e4007c",
	"middle green yellow":      "#acbf60",
	"midnight blue":            "#191970",
	"midnight blue1":           "#151b54",
	"midnight green":           "#004953",
	"midnight":                 "#2b1b17",
	"midnightblue":             "#191970",
	"mikado yellow":            "#ffc40c",
	"milk white":               "#fefcff",
	"milk":                     "#fdfff5",
	"mimosa":                   "#f0bf59",
	"mindaro":                  "#e3f988",
	"mint cream":               "#f5fffa",
	"mint green":               "#98ff98",
	"mint":                     "#3eb489",
	"mint1":                    "#00a170",
	"mintcream":                "#f5fffa",
	"mist blue":                "#646d7e",
	"misty rose":               "#ffe4e1",
	"misty rose1":              "#fbbbb9",
	"mistyrose":                "#ffe4e1",
	"moccasin":                 "#faebd7",
	"moccasin1":                "#ffe4b5",
	"moccasin2":                "#827839",
	"mocha":                    "#493d26",
	"moonstone blue":           "#73a9c2",
	"mordant red 19":           "#ae0c00",
	"moss green":               "#8a9a5b",
	"mountain meadow":          "#30ba8f",
	"mountbatten pink":         "#997a8d",
	"msu green":                "#18453b",
	"mughal green":             "#306030",
	"mulberry":                 "#c54b8c",
	"mustard":                  "#ffdb58",
	"myrtle green":             "#317873",
	"myrtle":                   "#21421e",
	"nadeshiko pink":           "#f6adc6",
	"napier green":             "#2a8000",
	"navajo white":             "#ffdead",
	"navajowhite":              "#ffdead",
	"navy blue":                "#000080",
	"navy peony":               "#223a5e",
	"navy purple":              "#9457eb",
	"navy":                     "#000080",
	"nebula green":             "#59e817",
	"nebulas blue":             "#3f69aa",
	"neon carrot":              "#ffa343",
	"neon fuchsia":             "#fe4164",
	"neon green":               "#39ff14",
	"neon pink":                "#f535aa",
	"neutral gray":             "#898e8c",
	"new car":                  "#214fc6",
	"new york pink":            "#d7837f",
	"niagara":                  "#578ca9",
	"night":                    "#0c090a",
	"non photo blue":           "#a4dded",
	"north texas green":        "#059033",
	"northern lights blue":     "#78c7c7",
	"nyanza":                   "#e9ffdb",
	"oak brown":                "#806517",
	"ocean blue":               "#2b65ec",
	"ocean boat blue":          "#0077be",
	"ochre":                    "#cc7722",
	"office green":             "#008000",
	"oil":                      "#3b3131",
	"old bamboo color":         "#5e644f",
	"old gold":                 "#cfb53b",
	"old heliotrope":           "#563c5c",
	"old lace":                 "#fdf5e6",
	"old lavender":             "#796878",
	"old moss green":           "#867e36",
	"old rose":                 "#c08081",
	"old silver":               "#848482",
	"oldlace":                  "#fdf5e6",
	"olive drab #7":            "#3c341f",
	"olive drab":               "#6b8e23",
	"olive":                    "#808000",
	"olivedrab":                "#6b8e23",
	"olivine":                  "#9ab973",
	"onyx":                     "#353839",
	"opera mauve":              "#b784a7",
	"orange (color wheel)":     "#ff7f00",
	"orange (ryb)":             "#fb9902",
	"orange gold":              "#d4a017",
	"orange peel":              "#ff9f00",
	"orange red":               "#ff4500",
	"orange salmon":            "#c47451",
	"orange tiger":             "#f96714",
	"orange":                   "#ffa500",
	"orangered":                "#ff4500",
	"orchid pink":              "#f28dcd",
	"orchid":                   "#da70d6",
	"orioles orange":           "#fb4f14",
	"otter brown":              "#654321",
	"outer space":              "#414a4c",
	"outrageous orange":        "#ff6e4a",
	"oxford blue":              "#002147",
	"pakistan green":           "#000060",
	"pakistan green1":          "#006600",
	"palatinate blue":          "#273be2",
	"palatinate purple":        "#682860",
	"pale aqua":                "#bcd4e6",
	"pale blue lily":           "#cfecec",
	"pale brown":               "#987654",
	"pale carmine":             "#af4035",
	"pale cerulean":            "#9bc4e2",
	"pale chestnut":            "#ddadaf",
	"pale copper":              "#da8a67",
	"pale cornflower blue":     "#abcdef",
	"pale dogwood":             "#edcdc2",
	"pale gold":                "#e6be8a",
	"pale goldenrod":           "#eee8aa",
	"pale green":               "#98fb98",
	"pale lavender":            "#dcd0ff",
	"pale magenta":             "#f984e5",
	"pale pink":                "#fadadd",
	"pale robin egg blue":      "#96ded1",
	"pale silver":              "#c9c0bb",
	"pale spring bud":          "#ecebbd",
	"pale taupe":               "#bc987e",
	"pale turquoise":           "#afeeee",
	"pale violet red":          "#db7093",
	"pale violet red1":         "#d16587",
	"palegoldenrod":            "#eee8aa",
	"palegreen":                "#98fb98",
	"paleturquoise":            "#afeeee",
	"palevioletred":            "#db7093",
	"paloma":                   "#9f9c99",
	"pansy purple":             "#78184a",
	"pantone turquoise":        "#41b6ab",
	"paolo veronese green":     "#009b7d",
	"papaya orange":            "#e56717",
	"papaya whip":              "#ffefd5",
	"papayawhip":               "#ffefd5",
	"paradise pink":            "#e63e62",
	"parchment":                "#ffffc2",
	"paris green":              "#50c878",
	"pastel blue":              "#aec6cf",
	"pastel blue1":             "#b4cfec",
	"pastel brown":             "#836953",
	"pastel gray":              "#cfcfc4",
	"pastel green":             "#77dd77",
	"pastel magenta":           "#f49ac2",
	"pastel orange":            "#ffb347",
	"pastel pink":              "#dea5a4",
	"pastel purple":            "#b39eb5",
	"pastel red":               "#ff6961",
	"pastel violet":            "#cb99c9",
	"pastel yellow":            "#fdfd96",
	"payne grey":               "#536878",
	"peach echo":               "#f7786b",
	"peach fuzz":               "#f87c56",
	"peach orange":             "#ffcc99",
	"peach pink":               "#fa9a85",
	"peach puff":               "#ffdab9",
	"peach yellow":             "#fadfad",
	"peach":                    "#ffe5b4",
	"peachpuff":                "#ffdab9",
	"pear":                     "#d1e231",
	"pearl aqua":               "#88d8c0",
	"pearl":                    "#fdeef4",
	"pearly purple":            "#b768a2",
	"pepper stem":              "#8d9440",
	"peridot":                  "#e6e200",
	"periwinkle":               "#ccccff",
	"periwinkle1":              "#e9cfec",
	"persian blue":             "#1c39bb",
	"persian green":            "#00a693",
	"persian indigo":           "#32127a",
	"persian orange":           "#d99058",
	"persian pink":             "#f77fbe",
	"persian red":              "#cc3333",
	"persian rose":             "#fe28a2",
	"persimmon":                "#ec5800",
	"peru":                     "#cd853f",
	"phthalo blue":             "#000f89",
	"phthalo green":            "#123524",
	"picton blue":              "#45b1e8",
	"pictorial carmine":        "#c30b4e",
	"pig pink":                 "#fdd7e4",
	"piggy pink":               "#fddde6",
	"pine green":               "#01796f",
	"pine green1":              "#387c44",
	"pine needle color":        "#454d32",
	"pink bow":                 "#c48189",
	"pink bubblegum":           "#ffdfdd",
	"pink cupcake":             "#e45e9d",
	"pink daisy":               "#e799a3",
	"pink lace":                "#ffddf4",
	"pink lavender":            "#d8b2d1",
	"pink lavender1":           "#dbb1cd",
	"pink lemonade":            "#e4287c",
	"pink peacock":             "#c62168",
	"pink pearl":               "#e7accf",
	"pink rose":                "#e7a1b0",
	"pink sherbet":             "#f78fa7",
	"pink yarrow":              "#ce3175",
	"pink":                     "#ffc0cb",
	"pink1":                    "#faafbe",
	"pistachio green":          "#9dc209",
	"pistachio":                "#93c572",
	"platinum":                 "#e5e4e2",
	"plum (traditional)":       "#8e4585",
	"plum pie":                 "#7d0541",
	"plum purple":              "#583759",
	"plum velvet":              "#7d0552",
	"plum":                     "#dda0dd",
	"plum1":                    "#b93b8f",
	"pomelo white":             "#f9ffe3",
	"pomelo":                   "#96a53c",
	"pomp and power":           "#86608e",
	"popstar":                  "#be4f62",
	"portland orange":          "#ff5a36",
	"powder blue":              "#b0e0e6",
	"powder blue1":             "#c6deff",
	"powderblue":               "#b0e0e6",
	"primrose yellow":          "#f6d155",
	"princess blue":            "#00539c",
	"princeton orange":         "#ff8f00",
	"prune":                    "#701c1c",
	"prussian blue":            "#003153",
	"psychedelic purple":       "#df00ff",
	"puce":                     "#cc8899",
	"puce1":                    "#7f5a58",
	"pullman brown":            "#644117",
	"pumpkin orange":           "#f87217",
	"pumpkin":                  "#ff7518",
	"purple (munsell)":         "#9f00c5",
	"purple amethyst":          "#6c2dc7",
	"purple daffodil":          "#b041ff",
	"purple dragon":            "#c38ec7",
	"purple flower":            "#a74ac7",
	"purple haze":              "#4e387e",
	"purple heart":             "#69359c",
	"purple iris":              "#571b7e",
	"purple jam":               "#6a287e",
	"purple mimosa":            "#9e7bff",
	"purple monster":           "#461b7e",
	"purple mountain majesty":  "#9678b6",
	"purple pizzazz":           "#fe4eda",
	"purple sage bush":         "#7a5dc7",
	"purple taupe":             "#50404d",
	"purple":                   "#800080",
	"purple1":                  "#8e35ef",
	"purpureus":                "#9a4eae",
	"quartz":                   "#51484f",
	"queen blue":               "#436b95",
	"queen pink":               "#e8ccd7",
	"quetzal green":            "#006e6d",
	"quiet gray":               "#bcbcbe",
	"quinacridone magenta":     "#8e3a59",
	"rackley":                  "#5d8aa8",
	"radiant orchid":           "#b565a7",
	"radical red":              "#ff355e",
	"rajah":                    "#fbab60",
	"raspberry glace":          "#915f6d",
	"raspberry pink":           "#e25098",
	"raspberry rose":           "#b3446c",
	"raspberry sorbet":         "#d2386c",
	"raspberry":                "#e30b5d",
	"raw umber":                "#826644",
	"razzle dazzle rose":       "#ff33cc",
	"razzmatazz":               "#e3256b",
	"razzmic berry":            "#8d4e85",
	"rebecca purple":           "#663399",
	"rebeccapurple":            "#663399",
	"red (munsell)":            "#f2003c",
	"red (ncs)":                "#c40233",
	"red (pigment)":            "#ed1c24",
	"red (ryb)":                "#fe2712",
	"red brown":                "#a52a2a",
	"red devil":                "#860111",
	"red dirt":                 "#7f5217",
	"red fox":                  "#c35817",
	"red orange":               "#ff5349",
	"red pear":                 "#7f4145",
	"red purple":               "#e40078",
	"red violet":               "#c71585",
	"red wine":                 "#990012",
	"red":                      "#ff0000",
	"redwood":                  "#a45a52",
	"regalia":                  "#522d80",
	"resolution blue":          "#002387",
	"rhythm":                   "#777696",
	"rich black":               "#004040",
	"rich brilliant lavender":  "#f1a7fe",
	"rich carmine":             "#d70040",
	"rich electric blue":       "#0892d0",
	"rich lavender":            "#a76bcf",
	"rich lilac":               "#b666d2",
	"rich maroon":              "#b03060",
	"rifle green":              "#444c38",
	"roast coffee":             "#704241",
	"robin egg blue":           "#00cccc",
	"robin egg blue1":          "#bdedff",
	"rocket metallic":          "#8a7f80",
	"rocky road":               "#5a3e36",
	"rogue pink":               "#c12869",
	"roman silver":             "#838996",
	"rose bonbon":              "#f9429e",
	"rose ebony":               "#674846",
	"rose gold":                "#b76e79",
	"rose gold1":               "#ecc5c0",
	"rose madder":              "#e32636",
	"rose pink":                "#ff66cc",
	"rose quartz":              "#aa98a9",
	"rose quartz1":             "#F7CAC9",
	"rose red":                 "#c21e56",
	"rose taupe":               "#905d5d",
	"rose vale":                "#ab4e52",
	"rose":                     "#ff007f",
	"rose1":                    "#e8adaa",
	"rosewood":                 "#65000b",
	"rosso corsa":              "#d40000",
	"rosy brown":               "#bc8f8f",
	"rosy brown1":              "#b38481",
	"rosy finch":               "#7f4e52",
	"rosybrown":                "#bc8f8f",
	"royal azure":              "#0038a8",
	"royal blue (traditional)": "#002366",
	"royal blue (web)":         "#041690",
	"royal blue1":              "#4169e1",
	"royal blue":               "#2b60de",
	"royal fuchsia":            "#ca2c92",
	"royal purple":             "#7851a9",
	"royalblue":                "#4169e1",
	"rubber ducky yellow":      "#ffd801",
	"ruber":                    "#ce4676",
	"rubine red":               "#d10056",
	"ruby red":                 "#9b111e",
	"ruby":                     "#e0115f",
	"ruddy brown":              "#bb6528",
	"ruddy pink":               "#e18e96",
	"ruddy":                    "#ff0028",
	"rufous":                   "#a81c07",
	"russet orange":            "#e47a2e",
	"russet":                   "#80461b",
	"russian green":            "#679267",
	"russian violet":           "#32174d",
	"rust":                     "#b7410e",
	"rust1":                    "#c36241",
	"rusty celadon":            "#898a74",
	"rusty red":                "#da2c43",
	"sacramento state green":   "#00563f",
	"saddle brown":             "#8b4513",
	"saddlebrown":              "#8b4513",
	"safety orange":            "#ff6700",
	"safety yellow":            "#eed202",
	"saffron":                  "#fbb917",
	"sage green":               "#848b79",
	"sage":                     "#bcb88a",
	"sailor blue":              "#2e4a62",
	"salad green":              "#a1c935",
	"salmon pink":              "#ff91a4",
	"salmon":                   "#fa8072",
	"salmon1":                  "#ff8c69",
	"sand dollar":              "#decdbf",
	"sand":                     "#c2b280",
	"sandstone":                "#786d5f",
	"sandstorm":                "#ecd540",
	"sandy brown":              "#f4a460",
	"sandy brown1":             "#ee9a4d",
	"sandy taupe":              "#967117",
	"sandybrown":               "#f4a460",
	"sangria":                  "#92000a",
	"sangria1":                 "#7e3817",
	"sap green":                "#507d2a",
	"sapphire blue":            "#0067a5",
	"sapphire blue1":           "#2554c7",
	"sapphire":                 "#0f52ba",
	"sargasso sea":             "#485167",
	"satin sheen gold":         "#cba135",
	"scarlet":                  "#ff2400",
	"schauss pink":             "#ff91af",
	"school bus yellow":        "#ffd800",
	"screamin green":           "#76ff7a",
	"sea blue":                 "#006994",
	"sea blue1":                "#c2dfff",
	"sea green":                "#4e8975",
	"sea shell":                "#fff5ee",
	"sea turtle green":         "#438d80",
	"seagreen":                 "#2e8b57",
	"seal brown":               "#321414",
	"seashell":                 "#fff5ee",
	"seaweed green":            "#437c17",
	"sedona":                   "#cc6600",
	"selective yellow":         "#ffba00",
	"sepia":                    "#704214",
	"sepia1":                   "#7f462c",
	"serenity":                 "#92A8D1",
	"shaded spruce":            "#005960",
	"shadow blue":              "#778ba5",
	"shadow":                   "#8a795d",
	"shampoo":                  "#ffcff1",
	"shamrock green":           "#347c17",
	"sheen green":              "#8fd400",
	"shimmering blush":         "#d98695",
	"shocking orange":          "#e55b3c",
	"shocking pink":            "#fc0fc0",
	"sienna1":                  "#882d17",
	"sienna":                   "#a0522d",
	"sienna2":                  "#8a4117",
	"silk blue":                "#488ac7",
	"silver chalice":           "#acacac",
	"silver lake blue":         "#5d89ba",
	"silver pink":              "#c4aead",
	"silver sand":              "#bfc1c2",
	"silver":                   "#c0c0c0",
	"sinopia":                  "#cb410b",
	"siskin sprout yellow":     "#7a942e",
	"skobeloff":                "#007474",
	"sky blue":                 "#87ceeb",
	"sky blue1":                "#6698ff",
	"sky magenta":              "#cf71af",
	"skyblue":                  "#87ceeb",
	"slate blue":               "#6a5acd",
	"slate blue1":              "#737ca1",
	"slate gray":               "#708090",
	"slate gra1y":              "#657383",
	"slate grey":               "#708090",
	"slateblue":                "#6a5acd",
	"slategray":                "#708090",
	"slategrey":                "#708090",
	"slime green":              "#bce954",
	"smalt":                    "#003399",
	"smitten":                  "#c84186",
	"smoke":                    "#738276",
	"smokey gray":              "#726e6d",
	"smokey topaz":             "#933d41",
	"snorkel blue":             "#034f84",

	"snow":                          "#fffafa",
	"soap":                          "#cec8ef",
	"soldier green":                 "#545a2c",
	"sonic silver":                  "#757575",
	"soybean":                       "#d2c29d",
	"space cadet":                   "#1d2951",
	"spanish bistre":                "#80755a",
	"spanish blue":                  "#0070b8",
	"spanish carmine":               "#d10047",
	"spanish crimson":               "#e51a4c",
	"spanish gray":                  "#989898",
	"spanish green":                 "#009150",
	"spanish orange":                "#e86100",
	"spanish pink":                  "#f7bfbe",
	"spanish red":                   "#e60026",
	"spanish sky blue":              "#00aae4",
	"spanish violet":                "#4c2882",
	"spanish viridian":              "#007f5c",
	"spiro disco ball":              "#0fc0fc",
	"spring bud":                    "#a7fc00",
	"spring crocus":                 "#bc70a4",
	"spring green":                  "#4aa02c",
	"springgreen":                   "#00ff7f",
	"st patrick blue":               "#23297a",
	"star command blue":             "#007bb8",
	"steel blue":                    "#4682b4",
	"steel blue1":                   "#4863a0",
	"steel pink":                    "#cc3366",
	"steelblue":                     "#4682b4",
	"stil de grain yellow":          "#fada5e",
	"stoplight go green":            "#57e964",
	"storeroom brown":               "#3d4035",
	"stormcloud":                    "#4f666a",
	"straw":                         "#e4d96f",
	"strawberry":                    "#fc5a8d",
	"sugar almond":                  "#935529",
	"sun yellow":                    "#ffe87c",
	"sunglow":                       "#ffcc33",
	"sunray":                        "#e3ab57",
	"sunrise orange":                "#e67451",
	"sunset orange":                 "#fd5e53",
	"super pink":                    "#cf6ba9",
	"sweet corn":                    "#f0ead6",
	"sweet lilac":                   "#e8b5ce",
	"tan brown":                     "#ece5b6",
	"tan":                           "#d2b48c",
	"tangelo":                       "#f94d00",
	"tangerine tango":               "#f05442",
	"tangerine":                     "#e78a61",
	"tango pink":                    "#e4717a",
	"taupe gray":                    "#8b8589",
	"taupe":                         "#483c32",
	"tawny port":                    "#672e3b",
	"tea green":                     "#d0f0c0",
	"tea green1":                    "#ccfb5d",
	"tea rose":                      "#f4c2c2",
	"teal blue":                     "#367588",
	"teal deer":                     "#99e6b3",
	"teal green":                    "#00827f",
	"teal":                          "#008080",
	"telemagenta":                   "#cf3476",
	"tenné (tawny)":                 "#cd5700",
	"terra cotta":                   "#e2725b",
	"terrarium moss":                "#616247",
	"thistle":                       "#d8bfd8",
	"thistle1":                      "#d2b9d3",
	"thulian pink":                  "#de6fa1",
	"tickle me pink":                "#fc89ac",
	"tiffany blue":                  "#0abab5",
	"tiffany blue1":                 "#81d8d0",
	"tiger orange":                  "#c88141",
	"tigerlily":                     "#e4583e",
	"tigers eye":                    "#e08d3c",
	"timberwolf":                    "#dbd7d2",
	"titanium yellow":               "#eee600",
	"toffee":                        "#755139",
	"tofu":                          "#eae6da",
	"tomato":                        "#ff6347",
	"toolbox":                       "#746cc0",
	"topaz":                         "#ffc87c",
	"tractor red":                   "#fd0e35",
	"trolley grey":                  "#808080",
	"tron blue":                     "#7dfdfe",
	"tropical rain forest":          "#00755e",
	"true blue":                     "#0073cf",
	"true red":                      "#c02034",
	"tufts blue":                    "#417dc1",
	"tulip pink":                    "#c25a7c",
	"tulip":                         "#ff878d",
	"tumbleweed":                    "#deaa88",
	"turkish rose":                  "#b57281",
	"turmeric":                      "#fe840e",
	"turquoise blue":                "#00ffef",
	"turquoise green":               "#a0d6b4",
	"turquoise1":                    "#30d5c8",
	"turquoise":                     "#40e0d0",
	"turquoise2":                    "#43c6db",
	"tuscan brown":                  "#6f4e37",
	"tuscan red":                    "#7c4848",
	"tuscan tan":                    "#a67b5b",
	"tuscan":                        "#fad6a5",
	"tuscany":                       "#c09999",
	"twilight lavender":             "#8a496b",
	"tyrian purple":                 "#66023c",
	"tyrian purple1":                "#c45aec",
	"ua blue":                       "#0033aa",
	"ua red":                        "#d9004c",
	"ube":                           "#8878c3",
	"ucla blue":                     "#536895",
	"ucla gold":                     "#ffb300",
	"ufo green":                     "#3cd070",
	"ultimate grey":                 "#939597",
	"ultra pink":                    "#ff6fff",
	"ultra violet":                  "#5f4b8b",
	"ultramarine blue":              "#4166f5",
	"ultramarine":                   "#120a8f",
	"umber":                         "#635147",
	"unbleached silk":               "#ffddca",
	"united nations blue":           "#5b92e5",
	"university of california gold": "#b78727",
	"unmellow yellow":               "#ffff66",
	"up forest green":               "#014421",
	"up maroon":                     "#7b1113",
	"upsdell red":                   "#ae2029",
	"urobilin":                      "#e1ad21",
	"usafa blue":                    "#004f98",
	"usc cardinal":                  "#990000",
	"usc gold":                      "#ffcc00",
	"utah crimson":                  "#d3003f",
	"valentine red":                 "#e55451",
	"valiant poppy":                 "#bd3d3a",
	"vampire gray":                  "#565051",
	"vanilla custard":               "#f3e0be",
	"vanilla ice":                   "#f38fa9",
	"vanilla":                       "#f3e5ab",
	"vegas gold":                    "#c5b358",
	"velvet maroon":                 "#7e354d",
	"venetian red":                  "#c80815",
	"venom green":                   "#728c00",
	"verdigris":                     "#43b3ae",
	"vermilion":                     "#e34234",
	"veronica":                      "#a020f0",
	"very peri":                     "#6667ab",
	"viola purple":                  "#7e587e",
	"violet (color wheel)":          "#7f00ff",
	"violet (ryb)":                  "#8601af",
	"violet blue":                   "#324ab2",
	"violet red":                    "#f75394",
	"violet red1":                   "#f6358a",
	"violet":                        "#8f00ff",
	"violet2":                       "#ee82ee",
	"violet1":                       "#8d38c9",
	"viridian green":                "#009698",
	"viridian":                      "#40826d",
	"vivid auburn":                  "#922724",
	"vivid burgundy":                "#9f1d35",
	"vivid cerise":                  "#da1d81",
	"vivid lime green":              "#a6d608",
	"vivid magenta":                 "#ba2649",
	"vivid orchid":                  "#cc00ff",
	"vivid sky blue":                "#00ccff",
	"vivid tangerine":               "#ffa089",
	"vivid violet":                  "#9f00ff",
	"volt":                          "#ceff00",
	"warm black":                    "#004242",
	"warm sand":                     "#c0ab8e",
	"water":                         "#ebf4fa",
	"watermelon pink":               "#fc6c85",
	"watermelon yellow":             "#eeff1b",
	"waterspout":                    "#a4f4f9",
	"wenge":                         "#645452",
	"wheat":                         "#f5deb3",
	"white smoke":                   "#f5f5f5",
	"white":                         "#ffffff",
	"whitesmoke":                    "#f5f5f5",
	"wild blue yonder":              "#a2add0",
	"wild orchid":                   "#d470a2",
	"wild strawberry":               "#ff43a4",
	"wild watermelon":               "#fc6c85",
	"willow dye":                    "#8c9e5e",
	"willow":                        "#9a8b4f",
	"willpower orange":              "#fd5800",
	"windows blue":                  "#357ec7",
	"windsor tan":                   "#a75502",
	"wine dregs":                    "#673147",
	"wine":                          "#722f37",
	"wisteria purple":               "#c6aec7",
	"wisteria":                      "#c9a0dc",
	"wood brown":                    "#c19a6b",
	"wood":                          "#966f33",
	"xanadu":                        "#738678",
	"yale blue":                     "#0f4d92",
	"yankees blue":                  "#1c2841",
	"yellow (munsell)":              "#efcc00",
	"yellow (ryb)":                  "#fefe33",
	"yellow green":                  "#52d017",
	"yellow orange":                 "#ffae42",
	"yellow rose":                   "#fff000",
	"yellow":                        "#ffff00",
	"yellow-green (crayola)":        " #c5e384",
	"yellowgreen":                   "#9acd32",
	"zaffre":                        "#0014a8",
	"zombie green":                  "#54c571",
}
