package htmlcolors

// ColorNames maps names to hex value. *A duplicate name
// will raise a compile-time error.* Might be duplicate
// colors ... (same color, different names). All colornames
// are lowercase for comparisons
// Duplicate color values exist in this table, but are skinned out
// in htmlColor.init().
// hex values mapped to multiple names should be RETAINED in this
// list for use of StringToColor. Similar colornames may be differentiated
// by adding a digit iff they map to different hex values.
// Same name-value combinations should be removed. Prefer names
// WITHOUT a space.

var ColorNames = map[string]string{
	"aliceblue":            "#f0f8ff",
	"antiquewhite":         "#faebd7",
	"aqua":                 "#00ffff",
	"aquamarine":           "#7fffd4",
	"azure":                "#f0ffff",
	"beige":                "#f5f5dc",
	"bisque":               "#ffe4c4",
	"black":                "#000000",
	"blanchedalmond":       "#ffebcd",
	"blue":                 "#0000ff",
	"blueviolet":           "#8a2be2",
	"brown":                "#a52a2a",
	"burlywood":            "#deb887",
	"cadetblue":            "#5f9ea0",
	"chartreuse":           "#7fff00",
	"chocolate":            "#d2691e",
	"coral":                "#ff7f50",
	"cornflowerblue":       "#6495ed",
	"cornsilk":             "#fff8dc",
	"crimson":              "#dc143c",
	"cyan":                 "#00ffff", // duplicate name for aqua
	"darkblue":             "#00008b",
	"darkcyan":             "#008b8b",
	"darkgoldenrod":        "#b8860b",
	"darkgray":             "#a9a9a9",
	"darkgreen":            "#006400",
	"darkgrey":             "#a9a9a9",
	"darkkhaki":            "#bdb76b",
	"darkmagenta":          "#8b008b",
	"darkolivegreen":       "#556b2f",
	"darkorange":           "#ff8c00",
	"darkred":              "#8b0000",
	"darksalmon":           "#e9967a",
	"darkseagreen":         "#8fbc8f",
	"darkslateblue":        "#483d8b",
	"darkslategray":        "#2f4f4f",
	"darkslategrey":        "#2f4f4f",
	"darkturquoise":        "#00ced1",
	"darkviolet":           "#9400d3",
	"deeppink":             "#ff1493",
	"deepskyblue":          "#00bfff",
	"dimgray":              "#696969",
	"dimgrey":              "#696969",
	"dodgerblue":           "#1e90ff",
	"firebrick":            "#b22222",
	"floralwhite":          "#fffaf0",
	"forestgreen":          "#228b22",
	"fuchsia":              "#ff00ff",
	"gainsboro":            "#dcdcdc",
	"ghostwhite":           "#f8f8ff",
	"gold":                 "#ffd700",
	"goldenrod":            "#daa520",
	"gray":                 "#808080",
	"grey":                 "#808080",
	"green":                "#008000",
	"greenyellow":          "#adff2f",
	"honeydew":             "#f0fff0",
	"hotpink":              "#ff69b4",
	"indianred":            "#cd5c5c",
	"indigo":               "#4b0082",
	"ivory":                "#fffff0",
	"khaki":                "#f0e68c",
	"lavender":             "#e6e6fa",
	"lavenderblush":        "#fff0f5",
	"lawngreen":            "#7cfc00",
	"lemonchiffon":         "#fffacd",
	"lightblue":            "#add8e6",
	"lightcoral":           "#f08080",
	"lightcyan":            "#e0ffff",
	"lightgoldenrodyellow": "#fafad2",
	"lightgray":            "#d3d3d3",
	"lightgreen":           "#90ee90",
	"lightgrey":            "#d3d3d3",
	"lightpink":            "#ffb6c1",
	"lightsalmon":          "#ffa07a",
	"lightseagreen":        "#20b2aa",
	"lightskyblue":         "#87cefa",
	"lightslategray":       "#778899",
	"lightslategrey":       "#778899",
	"lightsteelblue":       "#b0c4de",
	"lightyellow":          "#ffffe0",
	"lime":                 "#00ff00",
	"limegreen":            "#32cd32",
	"linen":                "#faf0e6",
	"magenta":              "#ff00ff", // alternate name: magenta
	"maroon":               "#800000",
	"mediumaquamarine":     "#66cdaa",
	"mediumblue":           "#0000cd",
	"mediumorchid":         "#ba55f3",
	"mediumpurple":         "#9370db",
	"mediumseagreen":       "#3cb371",
	"mediumslateblue":      "#7b68ee",
	"mediumspringgreen":    "#00fa9a",
	"mediumturquoise":      "#48d1cc",
	"mediumvioletred":      "#c71585",
	"midnightblue":         "#191970",
	"mintcream":            "#f5fffa",
	"mistyrose":            "#ffe4e1",
	"moccasin":             "#ffe4b5",
	"navajowhite":          "#ffdead",
	"navy":                 "#000080",
	"oldlace":              "#fdf5e6",
	"olive":                "#808000",
	"olivedrab":            "#6b8e23",
	"orange":               "#ffa500",
	"orangered":            "#ff4500",
	"orchid":               "#da70d6",
	"palegoldenrod":        "#eee8aa",
	"palegreen":            "#98fb98",
	"paleturquoise":        "#afeeee",
	"palevioletred":        "#db7093",
	"papayawhip":           "#ffefd5",
	"peachpuff":            "#ffdab9",
	"peru":                 "#cd853f",
	"pink":                 "#ffc0cb",
	"plum":                 "#dda0dd",
	"powderblue":           "#b0e0e6",
	"purple":               "#800080",
	"rebeccapurple":        "#663399",
	"red":                  "#ff0000",
	"rosybrown":            "#bc8f8f",
	"royalblue":            "#4169e1",
	"saddlebrown":          "#8b4513",
	"salmon":               "#fa8072",
	"sandybrown":           "#f4a460",
	"seagreen":             "#2e8b57",
	"seashell":             "#fff5ee",
	"sienna":               "#a0522d",
	"silver":               "#c0c0c0",
	"skyblue":              "#87ceeb",
	"slateblue":            "#6a5acd",
	"slategray":            "#708090",
	"slategrey":            "#708090",
	"snow":                 "#fffafa",
	"springgreen":          "#00ff7f",
	"steelblue":            "#4682b4",
	"tan":                  "#d2b48c",
	"teal":                 "#008080",
	"thistle":              "#d8bfd8",
	"tomato":               "#ff6347",
	"turquoise":            "#40e0d0",
	"violet":               "#ee82ee",
	"wheat":                "#f5deb3",
	"white":                "#ffffff",
	"whitesmoke":           "#f5f5f5",
	"yellow":               "#ffff00",
	"yellowgreen":          "#9acd32",
	/* Pantone Color-Of-Year */
	"cerulean":          "#9bb7d6",
	"fuschia rose":      "#c94476",
	"true red":          "#c02034",
	"aqua sky":          "#7ac5c5",
	"tigerlily":         "#e4583e",
	"blue turquoise":    "#4fb0ae",
	"sand dollar":       "#decdbf",
	"chili pepper":      "#9c1b31",
	"blue iris":         "#595ca1",
	"mimosa":            "#f0bf59",
	"pantone turquoise": "#41b6ab", // and duplicate detection proves it worth
	"honeysuckle":       "#da4f70",
	"tangerine tango":   "#f05442",
	"emerald":           "#169c78",
	"radiant orchid":    "#b565a7",
	"marsala":           "#955251",
	"rose quartz":       "#F7CAC9",
	"serenity":          "#92A8D1",
	"greenery":          "#88b04b",
	"ultra violet":      "#5f4b8b",
	"living coral":      "#ff6f61",
	"classic blue":      "#0f4c81",
	"ultimate grey":     "#939597",
	"illuminating":      "#f5df4d",
	"very peri":         "#6667ab",
	"vivid magenta":     "#ba2649",
	"peach fuzz":        "#f87c56",
	/* interesting colors from elsewhere */
	"amzn_0001": "#630f32", /* red matte */
	"amzn_0002": "#0F6340", /* greenish matte */

	"night":            "#0c090a",
	"gunmetal":         "#2c3539",
	"midnight":         "#2b1b17",
	"charcoal":         "#34282c",
	"dark slate grey":  "#25383c",
	"oil":              "#3b3131",
	"black cat":        "#413839",
	"iridium":          "#3d3c3a",
	"black eel":        "#463e3f",
	"black cow":        "#4c4646",
	"gray wolf":        "#504a4b",
	"vampire gray":     "#565051",
	"gray dolphin":     "#5c5858",
	"carbon gray":      "#625d5d",
	"ash gray":         "#666362",
	"cloudy gray":      "#6d6968",
	"smokey gray":      "#726e6d",
	"gray2":            "#736f6e",
	"granite":          "#837e7c",
	"battleship gray":  "#848482",
	"gray cloud":       "#b6b6b4",
	"gray goose":       "#d1d0ce",
	"platinum":         "#e5e4e2",
	"metallic silver":  "#bcc6cc",
	"blue gray":        "#98afc7",
	"light slate gray": "#6d7b8d",
	"slate gray":       "#657383",
	"jet gray":         "#616d7e",
	"mist blue":        "#646d7e",
	"marble blue":      "#566d7e",
	"slate blue":       "#737ca1",
	"steel blue":       "#4863a0",
	"blue jay":         "#2b547e",
	"dark slate blue":  "#2b3856",
	"midnight blue":    "#151b54",
	// "navy blue":        "#000080",
	"blue whale":       "#342d7e",
	"lapis blue":       "#15317e",
	"denim dark blue":  "#151b8d",
	"earth blue":       "#0000a0",
	"cobalt blue":      "#0020c2",
	"blueberry blue":   "#0041c2",
	"sapphire blue":    "#2554c7",
	"blue eyes":        "#1569c7",
	"royal blue":       "#2b60de",
	"blue orchid":      "#1f45fc",
	"blue lotus":       "#6960ec",
	"light slate blue": "#736aff",
	"windows blue":     "#357ec7",
	"glacial blue ice": "#368bc1",
	"silk blue":        "#488ac7",
	"blue ivy":         "#3090c7",
	"blue koi":         "#659ec7",
	"columbia blue":    "#87afc7",
	"baby blue":        "#95b9c7",
	"light steel blue": "#728fce",
	"ocean blue":       "#2b65ec",
	"blue ribbon":      "#306eff",
	"blue dress":       "#157dec",
	"dodger blue":      "#1589ff",
	// "cornflower blue":  "#6495ed",
	"sky blue":       "#6698ff",
	"butterfly blue": "#38acec",
	"iceberg":        "#56a5ec",
	"crystal blue":   "#5cb3ff",
	"deep sky blue":  "#3bb9ff",
	"denim blue":     "#79baec",
	"light sky blue": "#82cafa",
	"day sky blue":   "#82caff",
	"jeans blue":     "#a0cfec",
	"blue angel":     "#b7ceec",
	"pastel blue":    "#b4cfec",
	"sea blue":       "#c2dfff",
	"powder blue":    "#c6deff",
	"coral blue":     "#afdcec",
	"light blue":     "#addfff",
	"robin egg blue": "#bdedff",
	"pale blue lily": "#cfecec",
	// "light cyan":       "#e0ffff",
	"water": "#ebf4fa",
	// "aliceblue" : "#f0f8ff",
	// "azure" : "#f0ffff",
	"light slate":      "#ccffff",
	"light aquamarine": "#93ffe8",
	"electric blue":    "#9afeff",
	// "aquamarine" : "#7fffd4",
	"tron blue":            "#7dfdfe",
	"blue zircon":          "#57feff",
	"blue lagoon":          "#8eebec",
	"celeste":              "#50ebec",
	"blue diamond":         "#4ee2ec",
	"tiffany blue":         "#81d8d0",
	"cyan opaque":          "#92c7c7",
	"blue hosta":           "#77bfc7",
	"northern lights blue": "#78c7c7",
	"medium turquoise":     "#48cccd",
	"turquoise1":           "#43c6db",
	"jellyfish":            "#46c7c7",
	"blue green":           "#7bccb5",
	"macaw blue green":     "#43bfc7",
	"light sea green":      "#3ea99f",
	"dark turquoise":       "#3b9c9c",
	"sea turtle green":     "#438d80",
	"medium aquamarine":    "#348781",
	"greenish blue":        "#307d7e",
	"grayish turquoise":    "#5e7d7e",
	"beetle green":         "#4c787e",
	// "teal" : "#008080",
	"sea green":           "#4e8975",
	"camouflage green":    "#78866b",
	"sage green":          "#848b79",
	"hazel green":         "#617c58",
	"venom green":         "#728c00",
	"fern green":          "#667c26",
	"dark forest green":   "#254117",
	"medium sea green":    "#306754",
	"medium forest green": "#347235",
	"seaweed green":       "#437c17",
	"pine green":          "#387c44",
	"jungle green":        "#347c2c",
	"shamrock green":      "#347c17",
	"medium spring green": "#348017",
	"forest green":        "#4e9258",
	"green onion":         "#6aa121",
	"spring green":        "#4aa02c",
	"lime green":          "#41a317",
	"clover green":        "#3ea055",
	"green snake":         "#6cbb3c",
	"alien green":         "#6cc417",
	"green apple":         "#4cc417",
	"yellow green":        "#52d017",
	"kelly green":         "#4cc552",
	"zombie green":        "#54c571",
	"frog green":          "#99c68e",
	"green peas":          "#89c35c",
	"dollar bill green":   "#85bb65",
	"dark sea green":      "#8bb381",
	"iguana green":        "#9cb071",
	"avocado green":       "#b2c248",
	"pistachio green":     "#9dc209",
	"salad green":         "#a1c935",
	"hummingbird green":   "#7fe817",
	"nebula green":        "#59e817",
	"stoplight go green":  "#57e964",
	"algae green":         "#64e986",
	"jade green":          "#5efb6e",
	"emerald green":       "#5ffb17",
	"lawn green":          "#87f717",
	"chartreuse1":         "#8afb17",
	"dragon green":        "#6afb92",
	"mint green":          "#98ff98",
	"green thumb":         "#b5eaaa",
	"light jade":          "#c3fdb8",
	"tea green":           "#ccfb5d",
	"green yellow":        "#b1fb17",
	"slime green":         "#bce954",
	"goldenrod1":          "#edda74",
	"harvest gold":        "#ede275",
	"sun yellow":          "#ffe87c",
	// "yellow" : "#ffff00",
	"corn yellow":   "#fff380",
	"parchment":     "#ffffc2",
	"cream":         "#ffffcc",
	"lemon chiffon": "#fff8c6",
	// "cornsilk":            "#fff8dc",
	// "beige":               "#f5f5dc",
	"blonde": "#fbf6d9",
	// "antiquewhite":        "#faebd7",
	"champagne": "#f7e7ce",
	// "blanchedalmond":      "#ffebcd",
	"vanilla":             "#f3e5ab",
	"tan brown":           "#ece5b6",
	"peach":               "#ffe5b4",
	"mustard":             "#ffdb58",
	"rubber ducky yellow": "#ffd801",
	"bright gold":         "#fdd017",
	"golden brown":        "#eac117",
	"macaroni and cheese": "#f2bb66",
	"saffron":             "#fbb917",
	"beer":                "#fbb117",
	"cantaloupe":          "#ffa62f",
	"bee yellow":          "#e9ab17",
	"brown sugar":         "#e2a76f",
	// "burlywood":                "#deb887",
	"deep peach":               "#ffcba4",
	"ginger brown":             "#c9be62",
	"school bus yellow":        "#e8a317",
	"sandy brown":              "#ee9a4d",
	"fall leaf brown":          "#c8b560",
	"orange gold":              "#d4a017",
	"sand":                     "#c2b280",
	"cookie brown":             "#c7a317",
	"caramel":                  "#c68e17",
	"brass":                    "#b5a642",
	"khaki1":                   "#ada96e",
	"camel brown":              "#c19a6b",
	"bronze":                   "#cd7f32",
	"tiger orange":             "#c88141",
	"cinnamon":                 "#c58917",
	"bullet shell":             "#af9b60",
	"dark goldenrod":           "#af7817",
	"copper":                   "#b87333",
	"wood":                     "#966f33",
	"oak brown":                "#806517",
	"moccasin1":                "#827839",
	"army brown":               "#827b60",
	"sandstone":                "#786d5f",
	"mocha":                    "#493d26",
	"taupe":                    "#483c32",
	"coffee":                   "#6f4e37",
	"brown bear":               "#835c3b",
	"red dirt":                 "#7f5217",
	"sepia":                    "#7f462c",
	"orange salmon":            "#c47451",
	"rust":                     "#c36241",
	"red fox":                  "#c35817",
	"chocolate1":               "#c85a17",
	"sedona":                   "#cc6600",
	"papaya orange":            "#e56717",
	"halloween orange":         "#e66c2c",
	"pumpkin orange":           "#f87217",
	"construction cone orange": "#f87431",
	"sunrise orange":           "#e67451",
	"mango orange":             "#ff8040",
	"dark orange":              "#f88017",
	// "coral":                    "#ff7f50",
	"basket ball orange": "#f88158",
	"light salmon":       "#f9966b",
	"tangerine":          "#e78a61",
	"dark salmon":        "#e18b6b",
	"light coral":        "#e77471",
	"bean red":           "#f75d59",
	"valentine red":      "#e55451",
	"shocking orange":    "#e55b3c",
	// "red":                      "#ff0000",
	"scarlet":         "#ff2400",
	"ruby red":        "#f62217",
	"ferrari red":     "#f70d1a",
	"fire engine red": "#f62817",
	"lava red":        "#e42217",
	"love red":        "#e41b17",
	"grapefruit":      "#dc381f",
	"chestnut red":    "#c34a2c",
	"cherry red":      "#c24641",
	"mahogany":        "#c04000",
	"chilli pepper":   "#c11b17",
	"cranberry":       "#9f000f",
	"red wine":        "#990012",
	"burgundy":        "#8c001a",
	"chestnut":        "#954535",
	"blood red":       "#7e3517",
	"sienna1":         "#8a4117",
	"sangria":         "#7e3817",
	"firebrick1":      "#800517",
	"maroon1":         "#810541",
	"plum pie":        "#7d0541",
	"velvet maroon":   "#7e354d",
	"plum velvet":     "#7d0552",
	"rosy finch":      "#7f4e52",
	"puce":            "#7f5a58",
	"dull purple":     "#7f525d",
	"rosy brown":      "#b38481",
	"khaki rose":      "#c5908e",
	"pink bow":        "#c48189",
	"lipstick pink":   "#c48793",
	"rose":            "#e8adaa",
	"rose gold":       "#ecc5c0",
	"desert sand":     "#edc9af",
	"pig pink":        "#fdd7e4",
	"cotton candy":    "#fcdfff",
	"pink bubblegum":  "#ffdfdd",
	"misty rose":      "#fbbbb9",
	"pink1":           "#faafbe",
	"light pink":      "#faafba",
	"flamingo pink":   "#f9a7b0",
	"pink rose":       "#e7a1b0",
	"pink daisy":      "#e799a3",
	"cadillac pink":   "#e38aae",
	"carnation pink":  "#f778a1",
	"blush red":       "#e56e94",
	"hot pink":        "#f660ab",
	"watermelon pink": "#fc6c85",
	"violet red":      "#f6358a",
	"deep pink":       "#f52887",
	"pink cupcake":    "#e45e9d",
	"pink lemonade":   "#e4287c",
	"neon pink":       "#f535aa",
	// "magenta":               "#ff00ff",
	"dimorphotheca magenta": "#e3319d",
	"bright neon pink":      "#f433ff",
	"pale violet red":       "#d16587",
	"tulip pink":            "#c25a7c",
	"medium violet red":     "#ca226b",
	"rogue pink":            "#c12869",
	"burnt pink":            "#c12267",
	"bashful pink":          "#c25283",
	"dark carnation pink":   "#c12283",
	"plum1":                 "#b93b8f",
	"viola purple":          "#7e587e",
	"purple iris":           "#571b7e",
	"plum purple":           "#583759",
	// "indigo":                "#4b0082",
	"purple monster":     "#461b7e",
	"purple haze":        "#4e387e",
	"eggplant":           "#614051",
	"grape":              "#5e5a80",
	"purple jam":         "#6a287e",
	"dark orchid":        "#7d1b7e",
	"purple flower":      "#a74ac7",
	"medium orchid":      "#b048b5",
	"purple amethyst":    "#6c2dc7",
	"dark violet":        "#842dce",
	"violet1":            "#8d38c9",
	"purple sage bush":   "#7a5dc7",
	"lovely purple":      "#7f38ec",
	"purple1":            "#8e35ef",
	"aztech purple":      "#893bff",
	"medium purple":      "#8467d7",
	"jasmine purple":     "#a23bec",
	"purple daffodil":    "#b041ff",
	"tyrian purple":      "#c45aec",
	"crocus purple":      "#9172ec",
	"purple mimosa":      "#9e7bff",
	"heliotrope purple":  "#d462ff",
	"crimson1":           "#e238ec",
	"purple dragon":      "#c38ec7",
	"lilac":              "#c8a2c8",
	"blush pink":         "#e6a9ec",
	"mauve":              "#e0b0ff",
	"wisteria purple":    "#c6aec7",
	"blossom pink":       "#f9b7ff",
	"thistle1":           "#d2b9d3",
	"periwinkle":         "#e9cfec",
	"lavender pinocchio": "#ebdde2",
	"lavender blue":      "#e3e4fa",
	"pearl":              "#fdeef4",
	// "seashell":	`"#fff5ee",
	"milk white": "#fefcff",
	// "white" : "#ffffff",

}
